sonata_admin:
    title: 'E-Shop Admin'
    title_logo: /images/user.jpg
    dashboard:
        groups:
            app.admin.group.shop:
                label: Shop
                label_catalogue: App
                items:
                    - app.admin.product
                    - app.admin.category
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        edit: admin/custom_edit.html.twig

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
